version: '3.4'

networks:
  apinetwork:

services:
 mssql-container:
     image: mcr.microsoft.com/mssql/server:latest
     container_name: mssql-container
     environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=Tarek.1234 
     ports:
      - "8002:1433"
     networks:
      - apinetwork
     volumes:
      - mssql-container-data:/var/opt/mssql  

 itemsdotnetapi:
    image: ${DOCKER_REGISTRY-}itemsdotnetapi
    ports:
      - "8001:80"
    build:
      context: .
      dockerfile: ItemsDotNetApi/Dockerfile
    depends_on:
        - mssql-container
    networks:
     - apinetwork
volumes:
    mssql-container-data:    
    
  
